title: lgal
author: lausek
description: a small js-gallery

librarylink: https://raw.githubusercontent.com/lausek/lgal/master/lgal.js

highlighter: rouge

defaults:
  - scope:
  		path: "images"
    values:
      	image: true