title: lgal
author: lausek
baseurl: /lgal
description: "a small js-gallery"

library:
    repo: "https://github.com/lausek/lgal"
    link: "https://rawgit.com/lausek/lgal/master/lgal.js"
    style: "https://rawgit.com/lausek/lgal/master/lgal.css"

highlighter: rouge

plugins:
  - jekyll-octicons

sass:
    style: compressed

defaults:
  - scope:
      path: "images"
    values:
      image: true
