title: lgal
author: lausek
description: a small js-gallery

library:
	repo: https://github.com/lausek/lgal
	link: https://rawgit.com/lausek/lgal/master/lgal.js

highlighter: rouge

sass:
	style: compressed

defaults:
  - scope:
      path: "images"
    values:
      image: true